'use client';

import React from 'react';
import { motion } from 'framer-motion';
import { ArrowRight, CheckCircle2, Zap, BarChart3, Mail, FileText, Database } from 'lucide-react';
import Link from 'next/link';

const HeroSection = () => {
  return (
    <div className="min-h-screen flex items-center justify-center px-4 sm:px-6 lg:px-8 pt-20">
      <div className="max-w-5xl mx-auto w-full">
        <motion.div
          initial={{ opacity: 0, y: 20 }}
          animate={{ opacity: 1, y: 0 }}
          transition={{ duration: 0.8 }}
          className="text-center"
        >
          <div className="mb-6 inline-block">
            <span className="px-4 py-2 rounded-full bg-blue-500/10 border border-blue-500/30 text-blue-300 text-sm font-medium">
              ✨ AI-Powered Lead Automation
            </span>
          </div>

          <h1 className="text-5xl sm:text-7xl font-bold mb-6 bg-clip-text text-transparent bg-gradient-to-r from-blue-400 via-cyan-400 to-blue-400">
            Transform Leads into Insights
          </h1>

          <p className="text-xl text-gray-300 mb-8 max-w-2xl mx-auto leading-relaxed">
            Automatically enrich leads with AI-powered business audits. Generate personalized PDF reports, email prospects, and log data—all in seconds.
          </p>

          <div className="flex flex-col sm:flex-row gap-4 justify-center mb-16">
            <Link
              href="/submit"
              className="px-8 py-4 bg-gradient-to-r from-blue-500 to-cyan-500 rounded-lg font-semibold hover:shadow-lg hover:shadow-blue-500/50 transition-all duration-300 flex items-center justify-center gap-2"
            >
              Get Started <ArrowRight className="w-5 h-5" />
            </Link>
            <a
              href="#features"
              className="px-8 py-4 border border-gray-600 hover:border-gray-400 rounded-lg font-semibold transition-all duration-300"
            >
              Learn More
            </a>
          </div>

          <motion.div
            animate={{ y: [0, 10, 0] }}
            transition={{ duration: 2, repeat: Infinity }}
            className="opacity-70"
          >
            <div className="text-sm text-gray-400">Scroll to explore →</div>
          </motion.div>
        </motion.div>
      </div>
    </div>
  );
};

const FeaturesSection = () => {
  const features = [
    {
      icon: Zap,
      title: 'Instant Validation',
      description: 'Real-time email and domain validation with intelligent lead scoring',
    },
    {
      icon: BarChart3,
      title: 'Company Research',
      description: 'Automatic website analysis and company data enrichment',
    },
    {
      icon: FileText,
      title: 'AI Audits',
      description: 'Personalized business audits generated by advanced AI models',
    },
    {
      icon: Mail,
      title: 'Auto Email',
      description: 'Beautiful HTML emails with attached PDF reports sent automatically',
    },
    {
      icon: Database,
      title: 'Data Logging',
      description: 'Automatic Google Sheets integration and lead tracking',
    },
    {
      icon: CheckCircle2,
      title: 'Drive Storage',
      description: 'PDFs automatically saved to Google Drive with public links',
    },
  ];

  return (
    <section id="features" className="py-24 px-4">
      <div className="max-w-6xl mx-auto">
        <motion.div
          initial={{ opacity: 0, y: 20 }}
          whileInView={{ opacity: 1, y: 0 }}
          transition={{ duration: 0.8 }}
          className="text-center mb-16"
        >
          <h2 className="text-4xl sm:text-5xl font-bold mb-4">Powerful Features</h2>
          <p className="text-gray-400 text-lg">Everything you need for modern lead automation</p>
        </motion.div>

        <div className="grid md:grid-cols-2 lg:grid-cols-3 gap-8">
          {features.map((feature, idx) => (
            <motion.div
              key={idx}
              initial={{ opacity: 0, y: 20 }}
              whileInView={{ opacity: 1, y: 0 }}
              transition={{ duration: 0.5, delay: idx * 0.1 }}
              className="p-6 rounded-2xl bg-gradient-to-br from-gray-800/50 to-gray-900/50 border border-gray-700/50 hover:border-blue-500/50 transition-all duration-300 hover:shadow-lg hover:shadow-blue-500/10"
            >
              <feature.icon className="w-12 h-12 text-blue-400 mb-4" />
              <h3 className="text-xl font-semibold mb-2">{feature.title}</h3>
              <p className="text-gray-400">{feature.description}</p>
            </motion.div>
          ))}
        </div>
      </div>
    </section>
  );
};

const WorkflowSection = () => {
  const steps = [
    { title: 'Submit Form', description: 'Prospect enters company details' },
    { title: 'Validate Data', description: 'Instant validation and verification' },
    { title: 'Research', description: 'AI analyzes website and company' },
    { title: 'Generate Audit', description: 'Personalized business audit created' },
    { title: 'Create PDF', description: 'Professional report generated' },
    { title: 'Send Email', description: 'Beautiful email with PDF attached' },
    { title: 'Log Data', description: 'Automatic Google Sheets update' },
    { title: 'Store PDF', description: 'Save to Google Drive' },
  ];

  return (
    <section className="py-24 px-4">
      <div className="max-w-5xl mx-auto">
        <motion.div
          initial={{ opacity: 0, y: 20 }}
          whileInView={{ opacity: 1, y: 0 }}
          transition={{ duration: 0.8 }}
          className="text-center mb-16"
        >
          <h2 className="text-4xl sm:text-5xl font-bold mb-4">Automated Workflow</h2>
          <p className="text-gray-400 text-lg">Seamless end-to-end automation</p>
        </motion.div>

        <div className="grid md:grid-cols-2 gap-8">
          {steps.map((step, idx) => (
            <motion.div
              key={idx}
              initial={{ opacity: 0, x: idx % 2 === 0 ? -20 : 20 }}
              whileInView={{ opacity: 1, x: 0 }}
              transition={{ duration: 0.5, delay: idx * 0.1 }}
              className="flex gap-4 items-start"
            >
              <div className="w-10 h-10 rounded-full bg-gradient-to-br from-blue-500 to-cyan-500 flex items-center justify-center flex-shrink-0 font-bold">
                {idx + 1}
              </div>
              <div>
                <h4 className="font-semibold text-lg mb-1">{step.title}</h4>
                <p className="text-gray-400">{step.description}</p>
              </div>
            </motion.div>
          ))}
        </div>
      </div>
    </section>
  );
};

const CTASection = () => {
  return (
    <section className="py-24 px-4">
      <motion.div
        initial={{ opacity: 0, y: 20 }}
        whileInView={{ opacity: 1, y: 0 }}
        transition={{ duration: 0.8 }}
        className="max-w-3xl mx-auto text-center p-8 sm:p-16 rounded-3xl bg-gradient-to-r from-blue-600/20 to-purple-600/20 border border-blue-500/30"
      >
        <h2 className="text-4xl sm:text-5xl font-bold mb-6">Ready to Automate Your Leads?</h2>
        <p className="text-xl text-gray-300 mb-8">
          Start enriching and converting leads with AI-powered insights today.
        </p>
        <Link
          href="/submit"
          className="inline-flex px-8 py-4 bg-gradient-to-r from-blue-500 to-cyan-500 rounded-lg font-semibold hover:shadow-lg hover:shadow-blue-500/50 transition-all duration-300 items-center gap-2"
        >
          Start Your First Audit <ArrowRight className="w-5 h-5" />
        </Link>
      </motion.div>
    </section>
  );
};

export default function Home() {
  return (
    <main className="min-h-screen">
      <HeroSection />
      <FeaturesSection />
      <WorkflowSection />
      <CTASection />
    </main>
  );
}
